### ISSUE TITLE
No longer 'is' in daytime and nightstarker_night

### ISSUE THREAD

**Issue by midorineko** [xzion/dota2-gsi#4]
I was using this wonderful program, but couldn't get day/night cycles to work. Checked out the client and saw the issue. 

      { name: 'start',
        matchid: 3394219054,
        game_time: 778,
        clock_time: 638,
        daytime: true,
        nightstalker_night: false,
        game_state: 'DOTA_GAMERULES_STATE_GAME_IN_PROGRESS',
        win_team: 'none',
        customgamename: '',
        ward_purchase_cooldown: 0 }

If you have time to edit the read me and remove the 'is' in front of daytime and nightstalker_night other kiddos wont go down my rabbit hole.

**Comment by aarong11** [comment]
Fixed in https://github.com/xzion/dota2-gsi/pull/5

@midorineko 
@xzion

**Comment by xzion** [comment]
Fixed in #5 

thanks @aarong11
