### ISSUE TITLE
dota2-gsi not working in update 7.07

### ISSUE THREAD

**Issue by jlfalcon3589** [xzion/dota2-gsi#6]
It apologize for my English is not very good...

I have the test.cfg file within ...\game\dota\cfg\gamestate_integration\ with the following contents:

"dota2-gsi Configuration"
{
    "uri"               "http://localhost:3000/"
    "timeout"           "5.0"
    "buffer"            "0.1"
    "throttle"          "0.1"
    "heartbeat"         "30.0"
    "data"
    {
        "provider"      "1"
        "map"           "1"
        "player"        "1"
        "hero"          "1"
        "abilities"     "1"
        "items"         "1"
    }
    "auth"
    {
        "token"         "token1"
    }
}

I run the server:
node examples/events.js
//Output: Dota 2 GSI listening on port 3000

but when I run the client dota2 not shown anything on the console. It currently operates or no longer has any integration ??

regards

**Comment by xzion** [comment]
you need to name the file:
`gamestate_integration_test.cfg`

The Dota client will not load the file if the name doesn't start with "gamestate_integration"
